import type { RouteRecordRaw } from 'vue-router';
import {
  allowsInstanceTools,
  deploymentMode,
  routesForDeployment,
} from '@peanut-admin/ui-vue';
// Generated by the build config. Production builds export an empty array and
// contain no import edge to dev-tools.ts.
// eslint-disable-next-line import/no-unresolved
import instanceToolRoutes from 'virtual:peanut-instance-tool-routes';
import { pluginRoutes } from './plugin-contributions';

interface RouteModule {
  default?: RouteRecordRaw | RouteRecordRaw[];
}

// These are trusted source modules, not normalized records returned by the router.
const modules = import.meta.glob<RouteModule>(
  ['./modules/*.ts', '!./modules/dev-tools.ts'],
  { eager: true }
);
const externalModules = import.meta.glob<RouteModule>(
  './externalModules/*.ts',
  { eager: true }
);

function formatModules(
  sourceModules: Record<string, RouteModule>,
  result: RouteRecordRaw[]
): RouteRecordRaw[] {
  Object.keys(sourceModules).forEach((key) => {
    const defaultModule = sourceModules[key].default;
    if (!defaultModule) return;
    const moduleList = Array.isArray(defaultModule)
      ? [...defaultModule]
      : [defaultModule];
    result.push(...moduleList);
  });
  return result;
}

const configuredMode = import.meta.env.VITE_DEPLOYMENT_MODE;
const mode = deploymentMode(configuredMode);
const expectedInstanceTools =
  import.meta.env.DEV && allowsInstanceTools(configuredMode);
if (__PEANUT_INSTANCE_TOOLS_COMPILED__ !== expectedInstanceTools) {
  throw new Error('Instance-tool build policy is inconsistent.');
}
const instanceToolsAllowed =
  __PEANUT_INSTANCE_TOOLS_COMPILED__ && allowsInstanceTools(configuredMode);

export const appRoutes: RouteRecordRaw[] = routesForDeployment(
  [...formatModules(modules, []), ...instanceToolRoutes, ...pluginRoutes],
  mode,
  instanceToolsAllowed
);

export const appExternalRoutes: RouteRecordRaw[] = routesForDeployment(
  formatModules(externalModules, []),
  mode,
  instanceToolsAllowed
);
