import type { RouteRecordNormalized } from 'vue-router';
import {
  allowsInstanceTools,
  deploymentMode,
  routesForDeployment,
} from '@peanut-admin/ui-vue';
// Generated by the build config. Production builds export an empty array and
// contain no import edge to dev-tools.ts.
// eslint-disable-next-line import/no-unresolved
import instanceToolRoutes from 'virtual:peanut-instance-tool-routes';
import { pluginRoutes } from './plugin-contributions';

const modules = import.meta.glob(
  ['./modules/*.ts', '!./modules/dev-tools.ts'],
  { eager: true }
);
const externalModules = import.meta.glob('./externalModules/*.ts', {
  eager: true,
});

function formatModules(_modules: any, result: RouteRecordNormalized[]) {
  Object.keys(_modules).forEach((key) => {
    const defaultModule = _modules[key].default;
    if (!defaultModule) return;
    const moduleList = Array.isArray(defaultModule)
      ? [...defaultModule]
      : [defaultModule];
    result.push(...moduleList);
  });
  return result;
}

const configuredMode = import.meta.env.VITE_DEPLOYMENT_MODE;
const mode = deploymentMode(configuredMode);
const expectedInstanceTools =
  import.meta.env.DEV && allowsInstanceTools(configuredMode);
if (__PEANUT_INSTANCE_TOOLS_COMPILED__ !== expectedInstanceTools) {
  throw new Error('Instance-tool build policy is inconsistent.');
}
const instanceToolsAllowed =
  __PEANUT_INSTANCE_TOOLS_COMPILED__ && allowsInstanceTools(configuredMode);

export const appRoutes: RouteRecordNormalized[] = routesForDeployment(
  [...formatModules(modules, []), ...instanceToolRoutes, ...pluginRoutes],
  mode,
  instanceToolsAllowed
) as RouteRecordNormalized[];

export const appExternalRoutes: RouteRecordNormalized[] = routesForDeployment(
  formatModules(externalModules, []),
  mode,
  instanceToolsAllowed
) as RouteRecordNormalized[];
