-- peanut-release: 3.0.13
-- Append stable identities without renumbering historical records.
-- IDs 1..999999999 reserved for upstream system seeds; new custom IDs start at 1000000000.
SET @menu_identity_ddl=(SELECT IF(COUNT(*)=0,'ALTER TABLE `pa_system_menu` ADD COLUMN `menu_key` VARCHAR(160) NULL','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pa_system_menu' AND COLUMN_NAME='menu_key');
PREPARE menu_identity_stmt FROM @menu_identity_ddl;
EXECUTE menu_identity_stmt;
DEALLOCATE PREPARE menu_identity_stmt;
SET @menu_identity_ddl=(SELECT IF(COUNT(*)=0,'ALTER TABLE `pa_system_menu` ADD COLUMN `parent_key` VARCHAR(160) NULL','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pa_system_menu' AND COLUMN_NAME='parent_key');
PREPARE menu_identity_stmt FROM @menu_identity_ddl;
EXECUTE menu_identity_stmt;
DEALLOCATE PREPARE menu_identity_stmt;
SET @menu_identity_ddl=(SELECT IF(COUNT(*)=0,'ALTER TABLE `pa_system_menu` ADD COLUMN `module_key` VARCHAR(96) NOT NULL DEFAULT ''application''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pa_system_menu' AND COLUMN_NAME='module_key');
PREPARE menu_identity_stmt FROM @menu_identity_ddl;
EXECUTE menu_identity_stmt;
DEALLOCATE PREPARE menu_identity_stmt;
SET @menu_identity_ddl=(SELECT IF(COUNT(*)=0,'ALTER TABLE `pa_menu_definition` ADD COLUMN `is_show` TINYINT NOT NULL DEFAULT 1','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pa_menu_definition' AND COLUMN_NAME='is_show');
PREPARE menu_identity_stmt FROM @menu_identity_ddl;
EXECUTE menu_identity_stmt;
DEALLOCATE PREPARE menu_identity_stmt;
SET @menu_identity_ddl=(SELECT IF(COUNT(*)=0,'ALTER TABLE `pa_menu_definition` ADD COLUMN `is_cache` TINYINT NOT NULL DEFAULT 0','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pa_menu_definition' AND COLUMN_NAME='is_cache');
PREPARE menu_identity_stmt FROM @menu_identity_ddl;
EXECUTE menu_identity_stmt;
DEALLOCATE PREPARE menu_identity_stmt;
SET @menu_identity_ddl=(SELECT IF(COUNT(*)=0,'ALTER TABLE `pa_menu_definition` ADD COLUMN `is_disable` TINYINT NOT NULL DEFAULT 0','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pa_menu_definition' AND COLUMN_NAME='is_disable');
PREPARE menu_identity_stmt FROM @menu_identity_ddl;
EXECUTE menu_identity_stmt;
DEALLOCATE PREPARE menu_identity_stmt;
CREATE TEMPORARY TABLE menu_identity_seed (type CHAR(1), paths VARCHAR(200), perms VARCHAR(100), menu_key VARCHAR(160), module_key VARCHAR(96));
INSERT INTO menu_identity_seed VALUES ('M','/system','','core.organization','core');
INSERT INTO menu_identity_seed VALUES ('C','/system/menu','menu/lists','system.menu.lists','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','menu/add','system.menu.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','menu/edit','system.menu.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','menu/delete','system.menu.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/system/role','role/lists','system.role.lists','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','role/add','system.role.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','role/edit','system.role.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','role/delete','system.role.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/system/admin','admin/lists','system.admin.lists','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','admin/add','system.admin.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','admin/edit','system.admin.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','admin/delete','system.admin.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('M','/dashboard','','system.dashboard','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/dashboard/workplace','workbench/index','system.workbench.index','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/system/jobs','jobs/lists','system.jobs.lists','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','jobs/add','system.jobs.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','jobs/edit','system.jobs.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','jobs/delete','system.jobs.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('M','/member','','core.business','core');
INSERT INTO menu_identity_seed VALUES ('C','/member/list','member/lists','official.member.list','official.member');
INSERT INTO menu_identity_seed VALUES ('A','','member/detail','system.member.detail','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/status','system.member.status','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/adjustBalance','system.member.adjustbalance','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/add','system.member.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/edit','system.member.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/adjustMoney','system.member.adjustmoney','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','user.user/detail','system.user.user.detail','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','user.user/edit','system.user.user.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','user.user/adjustMoney','system.user.user.adjustmoney','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/profile/edit','system.member.profile.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/member/tag','member/tag/lists','official.member.tag','official.member');
INSERT INTO menu_identity_seed VALUES ('A','','member/tag/add','system.member.tag.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/tag/edit','system.member.tag.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','member/tag/delete','system.member.tag.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('M','/notice','','system.notice','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/notice/channel','notice/channel/detail','official.notification.channel','official.notification');
INSERT INTO menu_identity_seed VALUES ('A','','notice/channel/save','system.notice.channel.save','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/notice/template','notice/scene/lists','official.notification.template','official.notification');
INSERT INTO menu_identity_seed VALUES ('A','','notice/template/add','system.notice.template.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','notice/template/edit','system.notice.template.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','notice/template/delete','system.notice.template.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/notice/log','notice/log/lists','official.notification.log','official.notification');
INSERT INTO menu_identity_seed VALUES ('A','','notice/scene/detail','system.notice.scene.detail','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','notice/scene/save','system.notice.scene.save','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','notice/log/detail','system.notice.log.detail','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('M','/finance','','system.finance','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/finance/account-log','finance.account_log/lists','official.member.account-log','official.member');
INSERT INTO menu_identity_seed VALUES ('M','/app-setting','','core.applications','core');
INSERT INTO menu_identity_seed VALUES ('C','/app-setting/hot-search','setting/hot-search/config','system.setting.hot.search.config','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','setting/hot-search/save','system.setting.hot.search.save','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/app-setting/customer-service','setting/customer-service/config','system.setting.customer.service.config','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','setting/customer-service/save','system.setting.customer.service.save','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','setting/web-page/config','system.setting.web.page.config','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','setting/web-page/save','system.setting.web.page.save','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','setting/mini-program/config','system.setting.mini.program.config','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','setting/mini-program/save','system.setting.mini.program.save','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('M','/article','','core.content','core');
INSERT INTO menu_identity_seed VALUES ('C','/article/cate','article.articleCate/lists','official.article.categories','official.article');
INSERT INTO menu_identity_seed VALUES ('A','','article.articleCate/add','system.article.articlecate.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.articleCate/edit','system.article.articlecate.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.articleCate/delete','system.article.articlecate.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/article/list','article.article/lists','official.article.articles','official.article');
INSERT INTO menu_identity_seed VALUES ('A','','article.article/add','system.article.article.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.article/edit','system.article.article.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.article/delete','system.article.article.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.articleCate/detail','system.article.articlecate.detail','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.articleCate/updateStatus','system.article.articlecate.updatestatus','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.article/detail','system.article.article.detail','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','article.article/updateStatus','system.article.article.updatestatus','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/system/file','file/lists','official.file.library','official.file');
INSERT INTO menu_identity_seed VALUES ('A','','file/cate/lists','system.file.cate.lists','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','upload/image','system.upload.image','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','upload/video','system.upload.video','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','upload/file','system.upload.file','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','file/cate/add','system.file.cate.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','file/cate/edit','system.file.cate.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','file/cate/delete','system.file.cate.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','file/move','system.file.move','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','file/rename','system.file.rename','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','file/delete','system.file.delete','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/app-setting/pay','setting/pay/config','official.payment.settings','official.payment');
INSERT INTO menu_identity_seed VALUES ('C','/app-setting/channel','setting/channel/config','official.oauth.channels','official.oauth');
INSERT INTO menu_identity_seed VALUES ('C','/app-setting/decorate','setting/decorate/config','system.setting.decorate.config','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('C','/finance/recharge','recharge.recharge/lists','official.payment.recharge','official.payment');
INSERT INTO menu_identity_seed VALUES ('C','/finance/refund','finance.refund/record','official.payment.refund','official.payment');
INSERT INTO menu_identity_seed VALUES ('A','','recharge.recharge/refund','system.recharge.recharge.refund','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','recharge.recharge/refundAgain','system.recharge.recharge.refundagain','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','finance.refund/log','system.finance.refund.log','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('M','/system-settings','','core.system','core');
INSERT INTO menu_identity_seed VALUES ('M','/operations','','core.operations','core');
INSERT INTO menu_identity_seed VALUES ('C','/system/dept','dept/lists','system.dept.lists','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','dept/add','system.dept.add','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','dept/edit','system.dept.edit','peanut.admin');
INSERT INTO menu_identity_seed VALUES ('A','','dept/delete','system.dept.delete','peanut.admin');
CREATE TEMPORARY TABLE menu_identity_matches AS SELECT m.id,s.menu_key,s.module_key FROM pa_system_menu m JOIN menu_identity_seed s ON m.type=s.type AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(m.upstream_defaults_json,'$.paths')),m.paths)=s.paths AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(m.upstream_defaults_json,'$.perms')),m.perms)=s.perms;
CREATE TEMPORARY TABLE menu_identity_unique AS SELECT menu_key,MIN(id) AS id FROM menu_identity_matches GROUP BY menu_key HAVING COUNT(*)=1;
UPDATE pa_system_menu m JOIN menu_identity_matches s ON s.id=m.id JOIN menu_identity_unique u ON u.id=s.id AND u.menu_key=s.menu_key SET m.menu_key=s.menu_key,m.module_key=s.module_key WHERE m.menu_key IS NULL;
UPDATE pa_system_menu SET menu_key=CONCAT('custom.',REPLACE(UUID(),'-','')) WHERE menu_key IS NULL;
UPDATE pa_system_menu m LEFT JOIN pa_system_menu p ON p.id=m.pid SET m.parent_key=p.menu_key WHERE m.parent_key IS NULL AND m.pid<>0;
SET @menu_identity_ddl=(SELECT IF(COUNT(*)=0,'ALTER TABLE pa_system_menu ADD UNIQUE KEY uk_system_menu_key (menu_key)','SELECT 1') FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pa_system_menu' AND INDEX_NAME='uk_system_menu_key');
PREPARE menu_identity_stmt FROM @menu_identity_ddl;
EXECUTE menu_identity_stmt;
DEALLOCATE PREPARE menu_identity_stmt;
ALTER TABLE pa_system_menu MODIFY COLUMN menu_key VARCHAR(160) NOT NULL;
ALTER TABLE pa_system_menu AUTO_INCREMENT=1000000000;
UPDATE pa_menu_definition SET upstream_defaults_json=JSON_SET(upstream_defaults_json,'$.is_show',1,'$.is_cache',0,'$.is_disable',0) WHERE upstream_defaults_json IS NOT NULL AND JSON_EXTRACT(upstream_defaults_json,'$.is_show') IS NULL;
DROP TEMPORARY TABLE menu_identity_unique;
DROP TEMPORARY TABLE menu_identity_matches;
DROP TEMPORARY TABLE menu_identity_seed;
