CREATE TABLE `pa_data_permission_policy` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `role_id` BIGINT UNSIGNED NOT NULL,
  `protected_resource_id` BIGINT UNSIGNED NOT NULL,
  `resource_operation_id` BIGINT UNSIGNED NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `valid_from` DATETIME(3) NULL,
  `valid_until` DATETIME(3) NULL,
  `revision` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `reason` VARCHAR(300) NULL,
  `created_by_member_id` BIGINT UNSIGNED NOT NULL,
  `updated_by_member_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `archived_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_data_policy_tenant_id` (`tenant_id`, `id`),
  UNIQUE KEY `uk_data_policy` (`tenant_id`, `role_id`, `resource_operation_id`),
  KEY `idx_data_policy_active` (`tenant_id`, `role_id`, `status`, `valid_until`),
  CONSTRAINT `fk_data_policy_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `pa_tenant` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_data_policy_role` FOREIGN KEY (`tenant_id`, `role_id`) REFERENCES `pa_role` (`tenant_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_data_policy_resource` FOREIGN KEY (`protected_resource_id`) REFERENCES `pa_protected_resource` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_data_policy_operation` FOREIGN KEY (`resource_operation_id`) REFERENCES `pa_resource_operation` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_data_policy_creator` FOREIGN KEY (`tenant_id`, `created_by_member_id`) REFERENCES `pa_tenant_member` (`tenant_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_data_policy_updater` FOREIGN KEY (`tenant_id`, `updated_by_member_id`) REFERENCES `pa_tenant_member` (`tenant_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_data_policy_status` CHECK (`status` IN ('active', 'disabled', 'archived')),
  CONSTRAINT `chk_data_policy_dates` CHECK (`valid_until` IS NULL OR `valid_from` IS NULL OR `valid_until` > `valid_from`),
  CONSTRAINT `chk_data_policy_archived` CHECK ((`status` = 'archived' AND `archived_at` IS NOT NULL) OR `status` <> 'archived')
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
