CREATE TABLE `pa_source_read_grant` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_tenant_id` BIGINT UNSIGNED NOT NULL,
  `recipient_tenant_id` BIGINT UNSIGNED NOT NULL,
  `capability` VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `action` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `effect` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `object_id` BIGINT UNSIGNED NULL,
  `object_key` BIGINT UNSIGNED GENERATED ALWAYS AS (COALESCE(`object_id`, 0)) STORED,
  `fields_json` JSON NOT NULL,
  `status` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'active',
  `valid_from` DATETIME(3) NOT NULL,
  `valid_until` DATETIME(3) NULL,
  `granted_by_member_id` BIGINT UNSIGNED NOT NULL,
  `revoked_by_member_id` BIGINT UNSIGNED NULL,
  `revision` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `revoked_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_read_grant_identity` (`source_tenant_id`, `recipient_tenant_id`, `capability`, `action`, `effect`, `object_key`),
  KEY `idx_source_read_grant_recipient` (`recipient_tenant_id`, `capability`, `action`, `status`, `source_tenant_id`),
  CONSTRAINT `fk_source_read_grant_source_tenant` FOREIGN KEY (`source_tenant_id`) REFERENCES `pa_tenant` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_source_read_grant_recipient_tenant` FOREIGN KEY (`recipient_tenant_id`) REFERENCES `pa_tenant` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_source_read_grant_creator` FOREIGN KEY (`source_tenant_id`, `granted_by_member_id`) REFERENCES `pa_tenant_member` (`tenant_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_source_read_grant_revoker` FOREIGN KEY (`source_tenant_id`, `revoked_by_member_id`) REFERENCES `pa_tenant_member` (`tenant_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_source_read_grant_tenants` CHECK (`source_tenant_id` <> `recipient_tenant_id`),
  CONSTRAINT `chk_source_read_grant_capability` CHECK (`capability` REGEXP '^[a-z][a-z0-9.-]{2,159}$'),
  CONSTRAINT `chk_source_read_grant_action` CHECK (`action` REGEXP '^[a-z][a-z0-9.-]{1,63}$'),
  CONSTRAINT `chk_source_read_grant_effect` CHECK (`effect` IN ('allow', 'deny')),
  CONSTRAINT `chk_source_read_grant_status` CHECK (`status` IN ('active', 'revoked')),
  CONSTRAINT `chk_source_read_grant_fields` CHECK ((`effect` = 'allow' AND JSON_LENGTH(`fields_json`) > 0) OR (`effect` = 'deny' AND JSON_LENGTH(`fields_json`) = 0)),
  CONSTRAINT `chk_source_read_grant_window` CHECK (`valid_until` IS NULL OR `valid_until` > `valid_from`),
  CONSTRAINT `chk_source_read_grant_revoked` CHECK ((`status` = 'revoked' AND `revoked_by_member_id` IS NOT NULL AND `revoked_at` IS NOT NULL) OR (`status` = 'active' AND `revoked_by_member_id` IS NULL AND `revoked_at` IS NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
