CREATE TABLE `pa_data_permission_target_set` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `target_mode` VARCHAR(32) NOT NULL,
  `target_resource_key` VARCHAR(160) NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `revision` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `created_by_member_id` BIGINT UNSIGNED NOT NULL,
  `updated_by_member_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `archived_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_data_target_set_tenant_id` (`tenant_id`, `id`),
  KEY `idx_data_target_set_status` (`tenant_id`, `target_resource_key`, `status`, `id`),
  CONSTRAINT `fk_data_target_set_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `pa_tenant` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_data_target_set_creator` FOREIGN KEY (`tenant_id`, `created_by_member_id`) REFERENCES `pa_tenant_member` (`tenant_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_data_target_set_updater` FOREIGN KEY (`tenant_id`, `updated_by_member_id`) REFERENCES `pa_tenant_member` (`tenant_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_data_target_set_mode` CHECK (`target_mode` IN ('department', 'resource')),
  CONSTRAINT `chk_data_target_set_resource` CHECK ((`target_mode` = 'department' AND `target_resource_key` = 'core.department') OR (`target_mode` = 'resource' AND `target_resource_key` <> 'core.department')),
  CONSTRAINT `chk_data_target_set_status` CHECK (`status` IN ('active', 'disabled', 'archived')),
  CONSTRAINT `chk_data_target_set_archived` CHECK ((`status` = 'archived' AND `archived_at` IS NOT NULL) OR `status` <> 'archived')
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
