import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  realpathSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test, { after } from 'node:test';

// Source-maintenance regression, not an application installer. Required inputs:
// PEANUT_CRUD_EVIDENCE: traceable render() output manifest (generator,
// generator_sha256, output, frontend_files[{path, sha256, preview_operation}]).
// PEANUT_GENERATOR_COMMIT / PEANUT_FRONTEND_COMMIT: exact local Git objects.
// Optional PEANUT_CRUD_CORE_ROOT / PEANUT_CRUD_CORE_COMMIT selects compiled
// public Core entries; omission tests the target web application's native lock.
// Run: node --test web/tests/Productization/generated-crud-consumer.test.mjs
// Generated bytes are never patched. Failure workspaces and reports are retained.
const root = realpathSync(fileURLToPath(new URL('../../..', import.meta.url)));
const webRoot = path.join(root, 'web');
const native = createRequire(path.join(webRoot, 'package.json'));
const ts = native('typescript');
const sfc = native('vue/compiler-sfc');
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const read = (file) => readFileSync(file, 'utf8');
const git = (...args) =>
  execFileSync('git', args, { cwd: root, encoding: 'utf8' });
function commitInput(name) {
  const value = process.env[name];
  assert.match(
    value ?? '',
    /^[a-f0-9]{40}$/,
    `${name} must be an exact commit`
  );
  git('cat-file', '-e', `${value}^{commit}`);
  return value;
}
function within(parent, child) {
  const relative = path.relative(parent, child);
  return (
    relative !== '' &&
    relative !== '..' &&
    !relative.startsWith(`..${path.sep}`) &&
    !path.isAbsolute(relative)
  );
}
function ownedExisting(value, directory) {
  assert.ok(value, `A ${directory} path is required`);
  const result = realpathSync(path.resolve(root, value));
  assert.ok(
    within(path.join(root, '.local', directory), result),
    'Input must belong to this checkout'
  );
  return result;
}
function sourcePath(relative) {
  assert.match(
    relative,
    /^web\/src\/modules\/[a-z0-9-]+\/(?:[a-z0-9-]+\/)*(?:[a-z0-9-]+\.ts|index\.vue)$/
  );
  return relative;
}
function exactFile(file) {
  assert.ok(
    existsSync(file) && statSync(file).isFile(),
    `Missing consumer source: ${file}`
  );
  const parsed = path.parse(file);
  let directory = parsed.root;
  for (const part of file.slice(parsed.root.length).split(path.sep)) {
    assert.ok(
      readdirSync(directory).includes(part),
      `Incorrect path case: ${file}`
    );
    directory = path.join(directory, part);
  }
  return file;
}
const generatorCommit = commitInput('PEANUT_GENERATOR_COMMIT');
const frontendCommit = commitInput('PEANUT_FRONTEND_COMMIT');
const evidenceFile = ownedExisting(
  process.env.PEANUT_CRUD_EVIDENCE,
  'evidence'
);
const evidence = JSON.parse(read(evidenceFile));
assert.equal(
  evidence.generator,
  'server/app/adminapi/services/generator/GeneratorRenderService.php'
);
assert.equal(
  sha256(git('show', `${generatorCommit}:${evidence.generator}`)),
  evidence.generator_sha256
);
const outputRoot = ownedExisting(evidence.output, 'tmp');
assert.ok(
  Array.isArray(evidence.frontend_files) && evidence.frontend_files.length >= 3
);
const outputs = new Map();
for (const item of evidence.frontend_files) {
  sourcePath(item.path);
  assert.ok(!outputs.has(item.path), 'Duplicate generated output');
  const file = exactFile(path.join(outputRoot, item.path));
  assert.ok(
    within(outputRoot, realpathSync(file)),
    'Generated source escaped its output root'
  );
  assert.equal(
    sha256(readFileSync(file)),
    item.sha256,
    `Output changed: ${item.path}`
  );
  outputs.set(item.path, item);
}
const views = [...outputs.keys()].filter((file) => file.endsWith('/index.vue'));
assert.ok(
  views.length > 0,
  'A scaffold without a CRUD view is not a CRUD test'
);
const packageJson = JSON.parse(read(path.join(webRoot, 'package.json')));
const nativeConfig = JSON.parse(read(path.join(webRoot, 'tsconfig.json')));
assert.equal(nativeConfig.compilerOptions.strict, true);
for (const relative of [
  'web/package.json',
  'web/pnpm-lock.yaml',
  'web/tsconfig.json',
  'web/src/main.ts',
  'web/src/env.d.ts',
]) {
  assert.equal(
    sha256(readFileSync(path.join(root, relative))),
    sha256(git('show', `${frontendCommit}:${relative}`)),
    `Frontend input drift: ${relative}`
  );
}
const temporaryRoot = path.join(root, '.local/tmp/crud-consumer');
const reportRoot = path.join(root, '.local/evidence/crud-consumer');
mkdirSync(temporaryRoot, { recursive: true });
mkdirSync(reportRoot, { recursive: true });
const work = mkdtempSync(path.join(temporaryRoot, 'run-'));
const reportDirectory = mkdtempSync(path.join(reportRoot, 'run-'));
const replayWeb = path.join(work, 'web');
mkdirSync(replayWeb, { recursive: true });
symlinkSync(
  path.join(webRoot, 'node_modules'),
  path.join(replayWeb, 'node_modules'),
  'dir'
);
for (const relative of outputs.keys()) {
  const target = path.join(work, relative);
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, readFileSync(path.join(outputRoot, relative)), {
    flag: 'wx',
  });
}
const selectedCore = process.env.PEANUT_CRUD_CORE_ROOT;
const corePaths = {};
const runtimeAliases = [];
const coreIdentity = {
  mode: selectedCore ? 'selected-compiled' : 'native-lock',
  packages: {},
};
if (selectedCore) {
  const coreRoot = realpathSync(selectedCore);
  const commit = process.env.PEANUT_CRUD_CORE_COMMIT;
  assert.match(commit ?? '', /^[a-f0-9]{40}$/);
  assert.equal(
    execFileSync('git', ['-C', coreRoot, 'rev-parse', 'HEAD'], {
      encoding: 'utf8',
    }).trim(),
    commit
  );
  assert.equal(
    execFileSync('git', ['-C', coreRoot, 'status', '--porcelain'], {
      encoding: 'utf8',
    }).trim(),
    ''
  );
  coreIdentity.commit = commit;
  coreIdentity.root = coreRoot;
  for (const name of ['client', 'vue', 'ui-vue']) {
    const packageRoot = path.join(coreRoot, 'packages', name);
    const manifest = JSON.parse(read(path.join(packageRoot, 'package.json')));
    const entry = manifest.exports['.'];
    assert.equal(typeof entry.types, 'string');
    assert.equal(typeof entry.import, 'string');
    const types = exactFile(path.resolve(packageRoot, entry.types));
    const runtime = exactFile(path.resolve(packageRoot, entry.import));
    assert.ok(within(packageRoot, types) && within(packageRoot, runtime));
    corePaths[manifest.name] = [types];
    runtimeAliases.push({ find: manifest.name, replacement: runtime });
    coreIdentity.packages[manifest.name] = {
      version: manifest.version,
      types: sha256(read(types)),
      runtime: sha256(read(runtime)),
    };
  }
} else {
  for (const name of ['vue', 'ui-vue']) {
    const packageRoot = path.join(webRoot, 'node_modules/@peanut-admin', name);
    const manifest = JSON.parse(read(path.join(packageRoot, 'package.json')));
    coreIdentity.packages[manifest.name] = {
      version: manifest.version,
      manifest: sha256(read(path.join(packageRoot, 'package.json'))),
    };
  }
}
const report = {
  generatorCommit,
  frontendCommit,
  evidenceFile,
  generatorSha256: evidence.generator_sha256,
  frontendLockSha256: sha256(read(path.join(webRoot, 'pnpm-lock.yaml'))),
  core: coreIdentity,
  nativeTypeScript: ts.version,
  work,
  reportDirectory,
  generated: evidence.frontend_files,
  checks: {},
  scope:
    'Generated CRUD views and their API modules: native SFC typecheck and bundle. Contribution imports are path/dependency checked; no full route mount, browser, backend, migration or installation.',
};
after(() => {
  writeFileSync(
    path.join(reportDirectory, 'result.json'),
    JSON.stringify(report, null, 2) + '\n'
  );
  console.log(
    `CRUD_CONSUMER_REPORT ${path.join(reportDirectory, 'result.json')}`
  );
});
function script(file) {
  const text = read(path.join(outputRoot, file));
  if (!file.endsWith('.vue')) return text;
  const result = sfc.parse(text, { filename: file });
  assert.deepEqual(result.errors, []);
  assert.equal(result.descriptor.script, null);
  assert.equal(result.descriptor.scriptSetup?.lang, 'ts');
  return result.descriptor.scriptSetup.content;
}
function imports(file) {
  const tree = ts.createSourceFile(
    file,
    script(file),
    ts.ScriptTarget.Latest,
    true
  );
  const results = [];
  function visit(node) {
    if (
      (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
      node.moduleSpecifier
    ) {
      assert.ok(ts.isStringLiteral(node.moduleSpecifier));
      results.push(node.moduleSpecifier.text);
    }
    if (
      ts.isCallExpression(node) &&
      node.expression.kind === ts.SyntaxKind.ImportKeyword
    ) {
      assert.equal(node.arguments.length, 1);
      assert.ok(
        ts.isStringLiteral(node.arguments[0]),
        'Unregistered dynamic generated import'
      );
      results.push(node.arguments[0].text);
    }
    ts.forEachChild(node, visit);
  }
  visit(tree);
  return results;
}
function resolveLocal(file, specifier) {
  const base = specifier.startsWith('@/')
    ? `web/src/${specifier.slice(2)}`
    : path.posix.normalize(
        path.posix.join(path.posix.dirname(file), specifier)
      );
  assert.ok(base.startsWith('web/src/') && !base.split('/').includes('..'));
  for (const suffix of ['', '.ts', '.vue', '/index.ts']) {
    const relative = base + suffix;
    if (outputs.has(relative))
      return exactFile(path.join(outputRoot, relative));
    const host = path.join(root, relative);
    if (existsSync(host) && statSync(host).isFile()) return exactFile(host);
  }
  assert.fail(`Missing generated consumer import: ${file} -> ${specifier}`);
}

test('the replay contains unchanged, traceable real CRUD outputs', () => {
  for (const [relative, entry] of outputs)
    assert.equal(sha256(readFileSync(path.join(work, relative))), entry.sha256);
  report.checks.provenance = {
    passed: true,
    files: outputs.size,
    views: views.length,
  };
});

test('generated static/dynamic imports resolve to declared production dependencies and exact files', () => {
  const missing = [];
  let count = 0;
  for (const file of outputs.keys()) {
    for (const specifier of imports(file)) {
      count++;
      if (specifier.startsWith('.') || specifier.startsWith('@/')) {
        resolveLocal(file, specifier);
        continue;
      }
      const parts = specifier.split('/');
      const packageName = specifier.startsWith('@')
        ? parts.slice(0, 2).join('/')
        : parts[0];
      if (!Object.hasOwn(packageJson.dependencies, packageName)) {
        missing.push(`${file}: ${specifier}`);
        continue;
      }
      // The frontend consumes ESM exports; require.resolve would incorrectly
      // reject packages that intentionally expose only an import condition.
      if (!Object.hasOwn(corePaths, packageName))
        exactFile(fileURLToPath(import.meta.resolve(specifier)));
    }
  }
  report.checks.imports = { passed: missing.length === 0, count, missing };
  assert.deepEqual(
    missing,
    [],
    'Generated imports must use the actual target frontend dependencies'
  );
});

test('actual generated template components exist in the installed and registered UI', () => {
  const main = read(path.join(webRoot, 'src/main.ts'));
  assert.match(main, /import ElementPlus from 'element-plus'/);
  assert.match(main, /app\.use\(ElementPlus\)/);
  const ui = native('element-plus');
  const missing = [];
  const tags = [];
  for (const file of views) {
    const { descriptor } = sfc.parse(read(path.join(outputRoot, file)), {
      filename: file,
    });
    const compiledScript = sfc.compileScript(descriptor, {
      id: 'crud-consumer',
    });
    const template = sfc.compileTemplate({
      source: descriptor.template.content,
      filename: file,
      id: 'crud-consumer',
    });
    assert.deepEqual(template.errors, []);
    function visit(node) {
      if (node.type === 1 && node.tagType === 1) {
        const name = node.tag.replace(/(^|-)([a-z])/g, (_all, _dash, letter) =>
          letter.toUpperCase()
        );
        const imported =
          compiledScript.imports[node.tag] ?? compiledScript.imports[name];
        const explicit = imported && !imported.isType;
        tags.push(node.tag);
        if (
          !explicit &&
          !Object.hasOwn(ui, name) &&
          ![
            'Transition',
            'TransitionGroup',
            'KeepAlive',
            'Teleport',
            'Suspense',
          ].includes(name)
        )
          missing.push(`${file}: ${node.tag}`);
      }
      for (const child of node.children ?? []) visit(child);
    }
    visit(template.ast);
  }
  report.checks.components = { passed: missing.length === 0, tags, missing };
  assert.deepEqual(
    missing,
    [],
    'Unregistered components cannot become passing HTML custom elements'
  );
});

test('real generated Vue/API files pass native strict vue-tsc with actual component declarations', () => {
  const files = [...outputs.keys()]
    .filter((file) => file.endsWith('/index.vue') || file.endsWith('/api.ts'))
    .map((file) => path.join(work, file));
  const globalTypes = exactFile(
    path.join(webRoot, 'node_modules/element-plus/global.d.ts')
  );
  const configuration = {
    extends: path.join(webRoot, 'tsconfig.json'),
    compilerOptions: {
      paths: { '@/*': [path.join(webRoot, 'src/*')], ...corePaths },
    },
    vueCompilerOptions: { strictTemplates: true },
    files: [...files, path.join(webRoot, 'src/env.d.ts'), globalTypes],
    include: [],
    exclude: [],
  };
  const config = path.join(replayWeb, 'tsconfig.json');
  writeFileSync(config, JSON.stringify(configuration, null, 2) + '\n');
  const result = spawnSync(
    process.execPath,
    [native.resolve('vue-tsc/bin/vue-tsc.js'), '--noEmit', '--project', config],
    { cwd: replayWeb, encoding: 'utf8', timeout: 90000 }
  );
  writeFileSync(
    path.join(reportDirectory, 'vue-tsc.log'),
    (result.stdout ?? '') + (result.stderr ?? '')
  );
  report.checks.types = {
    passed: result.status === 0 && !result.error,
    exitCode: result.status,
    signal: result.signal,
    files,
    config,
  };
  assert.equal(result.error, undefined);
  assert.equal(result.status, 0, (result.stdout ?? '') + (result.stderr ?? ''));
});

test('the unchanged generated SFCs compile through native Vite/Vue without externalizing missing packages', async () => {
  const { build } = native('vite');
  const vuePlugin = native('@vitejs/plugin-vue');
  const logs = [];
  try {
    for (const [index, file] of views.entries()) {
      await build({
        configFile: false,
        root: replayWeb,
        publicDir: false,
        logLevel: 'error',
        plugins: [vuePlugin()],
        resolve: {
          alias: [
            { find: '@', replacement: path.join(webRoot, 'src') },
            ...runtimeAliases,
          ],
          dedupe: ['vue', 'pinia', 'element-plus'],
        },
        build: {
          lib: {
            entry: path.join(work, file),
            formats: ['es'],
            fileName: () => `crud-${index}.mjs`,
          },
          outDir: path.join(work, `dist-${index}`),
          emptyOutDir: false,
          minify: false,
        },
      });
      logs.push({ file, compiled: true });
    }
    report.checks.bundle = { passed: true, files: logs };
  } catch (error) {
    report.checks.bundle = { passed: false, files: logs, error: String(error) };
    throw error;
  }
});
