import type { RouteRecordRaw } from 'vue-router';
import type { PluginFrontendContribution } from '@peanut-admin/vue';
// The module is generated by the Vite plugin in config/vite.config.base.ts.
// eslint-disable-next-line import/no-unresolved
import lockedContributions from 'virtual:peanut-plugin-contributions';

// eslint-disable-next-line import/prefer-default-export
export const pluginRoutes: RouteRecordRaw[] = (
  lockedContributions as PluginFrontendContribution[]
)
  .flatMap((contribution) => contribution.routes)
  .map(
    (route): RouteRecordRaw =>
      ({
        ...route,
        meta: {
          ...route.meta,
          requiresAuth: route.meta?.requiresAuth === true,
          hideInMenu: true,
        },
      } as RouteRecordRaw)
  );
