CREATE TABLE `pa_ops_restore_evidence` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_key` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `backup_reference_key` CHAR(39) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `provider_key` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `target_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `manifest_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `evidence_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_commit` CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_tree` CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `target_deployment_resource_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `target_database_resource_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `target_runtime_resource_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `table_count` INT UNSIGNED NOT NULL,
  `schema_migration_count` INT UNSIGNED NOT NULL,
  `critical_table_count` INT UNSIGNED NOT NULL,
  `account_count` BIGINT UNSIGNED NOT NULL,
  `tenant_count` BIGINT UNSIGNED NOT NULL,
  `tenant_member_count` BIGINT UNSIGNED NOT NULL,
  `storage_file_count` BIGINT UNSIGNED NOT NULL,
  `storage_bytes` BIGINT UNSIGNED NOT NULL,
  `protected_runtime_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `verified_at` DATETIME(3) NOT NULL,
  `evidence_json` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ops_restore_task` (`task_key`),
  KEY `idx_ops_restore_verified` (`verified_at`, `id`),
  KEY `idx_ops_restore_backup` (`backup_reference_key`),
  CONSTRAINT `fk_ops_restore_task` FOREIGN KEY (`task_key`) REFERENCES `pa_ops_task` (`task_key`) ON DELETE RESTRICT,
  CONSTRAINT `fk_ops_restore_backup` FOREIGN KEY (`backup_reference_key`) REFERENCES `pa_ops_backup_evidence` (`backup_reference_key`) ON DELETE RESTRICT,
  CONSTRAINT `chk_ops_restore_provider` CHECK (`provider_key` = 'peanut.paired-db-files'),
  CONSTRAINT `chk_ops_restore_target` CHECK (`target_key` = 'isolated-new-target'),
  CONSTRAINT `chk_ops_restore_critical_tables` CHECK (`critical_table_count` = 6)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
